### ISSUE TITLE
NoMethodError: private method `open' called for URI:Module

### ISSUE THREAD

**Issue by comcava** [ankane/xgboost#5]
~/xgboost$ bundle exec rake vendor:all
Downloading libxgboost.so...
rake aborted!
NoMethodError: private method `open' called for URI:Module
/home/dan/xgboost/Rakefile:16:in `download_file'
/home/dan/xgboost/Rakefile:28:in `block (2 levels) in <top (required)>'
/home/dan/.rvm/gems/ruby-2.4.3/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/home/dan/.rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:24:in `eval'
/home/dan/.rvm/gems/ruby-2.4.3/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => vendor:all => vendor:linux
(See full trace by running task with --trace)

**Comment by ankane** [comment]
Hey @comcava, try removing `URI.` from that line (the Rakefile is designed for a more recent version of Ruby).

**Comment by comcava** [comment]
> Hey @comcava, try removing `URI.` from that line (the Rakefile is designed for a more recent version of Ruby).

Could you specify ruby version that's work with this gem?
